Add new voting system
Tech-With-Tim/twtcodejam.net pull request #44
Opened 2021-05-23 18:45 UTC by avibn

Added judging :mhmru:.
Let me know if I forgot to change anything back lol

2021-05-23 19:12 UTC, mohamed040406 requested changes

2021-05-23 19:12 UTC, mohamed040406 commented on TWT/apps/timathon/views/judge/judge.py
> +                discord_members.append(new_member)
shouldn't this also go inside the `else` block? 👀 
if the user is not found (which shouldn't happen anyway) it shouldn't add any user to the `discord_members` list

2021-05-23 20:08 UTC, mohamed040406 approved these changes

2021-05-24 03:59 UTC, Correct-skill approved these changes
hopefully this is working lol :p

2021-05-24 07:41 UTC, avibn commented
lol I'm hoping too :lamo:

2021-05-24 07:51 UTC, Springhunk commented
When you talk through github pull request comments 😳😳

2021-06-02 12:15 UTC, avibn commented
- Migrating bootstrap caused some ui issues, so most of the commits are slight UI fixes.
- Changed up the homepage a bit.

2021-06-02 18:04 UTC, Correct-skill approved these changes
Tested... works fine ui looks better :smilecat:

2021-06-03 14:57 UTC, avibn commented
Todo:
- [ ] Remove last criterion

and then we should be done for now

2021-06-03 15:31 UTC, merged