Update the directory structure after like 7 months
Tech-With-Tim/twtcodejam.net pull request #46
Opened 2021-06-06 14:37 UTC by akionsight

it had been severely outdated so just updated it

2021-06-06 14:37 UTC, akionsight commented
O ok checks passed

2021-06-06 20:24 UTC, takos22 requested changes
You need to cd in the right dir and replace the useless files (migrations and fonts) with `...`

2021-06-06 20:24 UTC, takos22 commented on STRUCTURE.md
> +└── twtcodejam.net
You need to be inside this dir when doing the tree command

2021-06-06 20:24 UTC, takos22 commented on STRUCTURE.md
> +    │   │   │   │   ├── 0001_initial.py
Remove these files and replace them with `...`

2021-06-06 20:24 UTC, takos22 commented on STRUCTURE.md
> +    │   │   │   │   ├── 0001_initial.py
Remove these files and replace them with `...`

2021-06-06 20:24 UTC, takos22 commented on STRUCTURE.md
> +    │   │   │   ├── Lovelo-Black.woff
Remove these files and replace them with `...`

2021-06-14 03:49 UTC, mohamed040406 commented
why do we even need a directory tree?

2021-06-14 05:10 UTC, akionsight commented
> 
> 
> why do we even need a directory tree?

Yeah you know what, I thought about it for a little while. and I think we do not need one
I think I should close the PR and the Directory Structure should be removed

2021-06-14 05:10 UTC, closed without merging