Update notification messages
Tech-With-Tim/twtcodejam.net pull request #70
Opened 2021-09-28 04:48 UTC by classPythonAddike

PR to implement #59 👀

2021-09-28 17:59 UTC, takos22 requested changes

2021-09-28 17:59 UTC, takos22 commented on TWT/apps/timathon/views/create_team.py
> +                fields=[{"name": "Error", "value": "There is no codejam ongoing"}],
`There are no ongoing code-jams`

2021-09-28 17:59 UTC, takos22 commented on TWT/apps/timathon/views/create_team.py
> +                request, messages.WARNING, "Team Submissions are closed right now"
`Team creation period is over`

2021-09-28 17:59 UTC, takos22 commented on TWT/apps/timathon/views/submission_list_view.py
> +                request, messages.INFO, "There is no ongoing challenge right now."
`There are no ongoing challenges`

2021-09-29 00:55 UTC, classPythonAddike commented
Will do the changes in an hour :cheemsdorime:

2021-09-29 13:12 UTC, classPythonAddike commented
@takos22 committed the changes :mhm:

2021-09-29 15:57 UTC, takos22 approved these changes

2021-09-29 15:57 UTC, merged